name: Update Time Badge
on:
  schedule:
    - cron: "0 0 * * *"  # 每天 00:00 UTC 运行（北京时间 08:00）
  workflow_dispatch:

jobs:
  update-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Calculate time difference
        run: |
          START_DATE="2020-12-08"
          CURRENT_DATE=$(date -u +"%Y-%m-%d")

          # 计算总天数
          DAYS_TOTAL=$(( ( $(date -d "$CURRENT_DATE" +%s) - $(date -d "$START_DATE" +%s) ) / 86400 ))

          # 计算年、月、日
          YEARS=$((DAYS_TOTAL / 365))
          REMAINING_DAYS=$((DAYS_TOTAL % 365))
          MONTHS=$((REMAINING_DAYS / 30))
          DAYS=$((REMAINING_DAYS % 30))

          # 生成 JSON 文件
          MESSAGE="${YEARS}年:${MONTHS}:${DAYS}日"
          echo "{\"schemaVersion\": 1, \"label\": \"工作年限\", \"message\": \"$MESSAGE\", \"color\": \"blue\"}" > time.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add time.json
          git commit -m "Update time badge" || exit 0
          git push
